---
path: github.com/mediocregopher/bananaq
deps:
    - loc: github.com/mediocregopher/lever
    - loc: github.com/mediocregopher/pubsubch
    - loc: github.com/mediocregopher/radix.v2
    - loc: github.com/stretchr/testify
